AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'lib/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - '**/*.json.jbuilder'
    - 'vendor/bundle/**/*'

Style/SymbolArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FileName:
  Exclude:
    - Gemfile

# Want to refactor some stuff? Remove these.
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 100
  Exclude:
    - 'db/migrate/*'
Metrics/LineLength:
  Max: 150
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods:
    - scope
    - configure
    - draw
    - define
    - test
