# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= AppConfig['data_explorer']['database_url'] %>

    timeout: 30

    cache:
      mode: slow          # Cache queries that exceed slow_timeout seconds
      expires_in: 60      # Cache expires in expires_in minutes
      slow_threshold: 5

    use_transaction: true

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      post_id: "/post/{value}"
      author_id: "/stackusers/{value}"
      reason_id: "/reason/{value}"

    smart_columns:
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
# user_class: User

user_name: username

# optional auth method to use as a before_action (default: nil)
# before_action: :authenticate!

# email to send checks from
# from_email: blazer@example.org

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"
