common: &common
  smoke_detector:
    key: 'smokey_key'
  ses_smtp_credentials:
    username: 'xxx'
    password: 'yyy'
  github:
    secret_token: 'xxyyzz'
    username: 'username'
    password: 'p455w0rd'
  stack_exchange:
    client_secret: 'sekrit'
    client_id: '1234'
    key: 'key'
    redirect_uri: 'https://domain.com/authentication/redirect_target'
    login_redirect_uri: 'https://domain.com/authentication/login_redirect_target'
    token_aes_key: 'random_bytes_here'
  travis_ci:
    token: 'gibberish'

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

